language: python
services:
- docker
script:
- |
  if [ "$TRAVIS_BRANCH" = "master" ]; then
    fbn_token_url="MASTER_FBN_TOKEN_URL"
    fbn_username="MASTER_FBN_USERNAME"
    fbn_password="MASTER_FBN_PASSWORD"
    fbn_clientid="MASTER_FBN_CLIENT_ID"
    fbn_client_secret="MASTER_FBN_CLIENT_SECRET"
    fbn_lusid_api_url="MASTER_FBN_LUSID_API_URL"
    fbn_app_name="MASTER_FBN_APP_NAME"
  else
    fbn_token_url="DEVELOP_FBN_TOKEN_URL"
    fbn_username="DEVELOP_FBN_USERNAME"
    fbn_password="DEVELOP_FBN_PASSWORD"
    fbn_clientid="DEVELOP_FBN_CLIENT_ID"
    fbn_client_secret="DEVELOP_FBN_CLIENT_SECRET"
    fbn_lusid_api_url="DEVELOP_FBN_LUSID_API_URL"
    fbn_app_name="DEVELOP_FBN_APP_NAME"
  fi
  export FBN_TOKEN_URL=${!fbn_token_url} \
  export FBN_USERNAME=${!fbn_username} \
  export FBN_PASSWORD=${!fbn_password} \
  export FBN_CLIENT_ID=${!fbn_clientid} \
  export FBN_CLIENT_SECRET=${!fbn_client_secret} \
  export FBN_LUSID_API_URL=${!fbn_lusid_api_url} \
  export FBN_APP_NAME=${!fbn_app_name}
  cd performance_engine
  docker-compose up --abort-on-container-exit
notifications:
  slack:
    rooms:
      secure: "Z3kky5rnkdKVSkpMB/PHC1C8reTLZUTzaU2OcOnG36g4BR2gZY/6US1A+So3MDUQzjhvAZGNzkXNAU6R06UsbDIAU8kDHJPgJn67n8HcCfD1OcuIkAqnxMRfKlnubwoO7vfSQXRNHlnFBSQLDLxTEDmcvxf+eib73U2Gpo5ICHnx0gFFEIRvydVF7r3KSIukDxycg5hC/Rvwh0FbQ6qdYpRAo1t0rTDFxT/cNznEQoXhpyYPTeUQPbN4IhpDmOLWPni0941spDDbcmCugGo4KuxVPkO7islzP6Eggl2lxUuCoTLl4saExAese3z2bazykYDpy+2W8Ap1sOlT4anFL3mCVmJwAjPqEWioT9NOOoTGPApbpH4g5LFcUndrR7NfttNqFCwHSO8qscEi49Dlf7mu85IIxQq5nVY8t1agG56c7lG10GfAEzVKr676QV0xMjHDyynm4UQuhJdWBQalQo5HK4gXSpg4YdPr4OIUOPaYjpp1nPT6Pp2cR5QdKxFJNmDwmWKRerl5Al3cSuPP7tjakyGHQ8tc7rSKTEEYgsy566p724Uw/G/Y0wE07Kv4rB97T+Bm6hNexWqOmw172f/XHGpRcsRoqPOxUU/T9GPqRUAfyXV5gHMPVIDUoLBY5ZbWt3AYSngsTm2nOl5BTaXnaaGxnjpa24dFTFVxT7I="
    on_failure: always